language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --omit=tests/* setup.py test
after_success:
  - coveralls